// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQry9h_EOv4ohBnpnwuxRlki2BO_MXMI8',
    appId: '1:1057701588403:web:fb2f76916222f66a11afc6',
    messagingSenderId: '1057701588403',
    projectId: 'aartas-clinisquare',
    authDomain: 'aartas-clinisquare.firebaseapp.com',
    storageBucket: 'aartas-clinisquare.appspot.com',
    measurementId: 'G-DEE9C7JME4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3QT0wfuVgbrw29vGjj-sLZ1T1xDuLbw',
    appId: '1:1057701588403:android:990c7ddb6db46ea811afc6',
    messagingSenderId: '1057701588403',
    projectId: 'aartas-clinisquare',
    storageBucket: 'aartas-clinisquare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7S22X4E8BeCK6Cb_M4BhiXLdI6diZEIk',
    appId: '1:1057701588403:ios:d2a8c8cc4b4bf3e611afc6',
    messagingSenderId: '1057701588403',
    projectId: 'aartas-clinisquare',
    storageBucket: 'aartas-clinisquare.appspot.com',
    iosBundleId: 'com.example.clinisquareAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7S22X4E8BeCK6Cb_M4BhiXLdI6diZEIk',
    appId: '1:1057701588403:ios:2753b95fea657d3e11afc6',
    messagingSenderId: '1057701588403',
    projectId: 'aartas-clinisquare',
    storageBucket: 'aartas-clinisquare.appspot.com',
    iosBundleId: 'com.example.clinisquareAuth.RunnerTests',
  );
}
